### ISSUE TITLE
Create a new resource group during creating IoTHub would fail randomly

### ISSUE THREAD

**Issue by lirenhe** [microsoft/vscode-azure-iot-toolkit#103]
In IoT workbench, in the first step of Cloud Provision, when we create a new IoT Hub and try to create a resource group from VS Code, it automatically and quickly fails with an error “Provision cancelled”.

**Comment by formulahendry** [comment]
Should be similar issue as #83

**Comment by formulahendry** [comment]
@lirenhe VS Code team says there are some changes in v1.25: https://github.com/Microsoft/vscode/issues/48879#issuecomment-407075904 Does the issue still exist in v1.25?

**Comment by formulahendry** [comment]
Fixed in VS Code side
