### ISSUE TITLE
The API of create IoTHub should support input parameter of subscription id and resource group

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-azure-iot-toolkit#117]
Currently, such parameter is not supported. 
User need to pick up subscription every time.

Api provided by Azure function extension: 

const functionAppId: string = await vscode.commands.executeCommand<string>('azureFunctions.createFunctionApp', '00000000-0000-0000-0000-000000000000');

**Comment by lirenhe** [comment]
Just discussed with Azure Functions team, they will also add the input parameter of resoucegroup name in their API in next release, could you also support the parameter of resource group?

**Comment by formulahendry** [comment]
Added in v1.4.0
