### ISSUE TITLE
Generate Code

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-azure-iot-toolkit#118]
Flow:
1. Right-click on a device and select 'Generate Code'
2. Drop-down list: select language (Node.js, Python, HTTP...)
3. Drop-down list: select code type (Send D2C message, Monitor D2C message..)
4. Generate code and show in VS Code 

Languages:
- [x] Node.js
- [x] Python
- [x] REST API
- [x] Java
- [x] C#
- [x] F#
- [x] Go
- [x] PHP
- [x] Ruby

**Comment by formulahendry** [comment]
F# support released in v1.5.0

**Comment by tuckstarrydell** [comment]
#554
