### ISSUE TITLE
use device twin desired properties to enter a target condition failed

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#122]
Reference from https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-monitor-cli#create-a-deployment 

--target-condition - Enter a target condition to determine which devices will be targeted with this deployment. The condition is based on device twin tags or device twin desired properties and should match the expression format. For example, tags.environment='test' or properties.desired.devicemodel='4000x'. 

![image](https://user-images.githubusercontent.com/35018765/42861602-434a185c-8a8e-11e8-9df7-cc6835cb9be3.png)

**Comment by formulahendry** [comment]
It is doc bug, open an issue for them: https://github.com/MicrosoftDocs/azure-docs/issues/11891

properties.desired.devicemodel='4000x' should be properties.reported.devicemodel='4000x'
