### ISSUE TITLE
Show correct running status for IoT Edge modules

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-azure-iot-toolkit#125]
Upstream issue: https://github.com/Azure/iotedge/issues/39

**Comment by shizn** [comment]
@formulahendry any updates on this one? Thanks.

**Comment by formulahendry** [comment]
We have a clean description now: https://github.com/Microsoft/vscode-azure-iot-toolkit/wiki/FAQ#how-to-understand-the-connection-state-and-running-status-of-modules
