### ISSUE TITLE
[ubuntu] [Generate Code]"Run Code" menu is not display

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#134]
steps:
1. right click a device and select Generate Code --Node js -- send D2C message
2. Run 'npm install azure-iot-device-mqtt' to install the required libraries
3. right click  the code and can't find "Run Code" menu

**Comment by formulahendry** [comment]
Please install the https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner if you want to use "Run Code" menu
