### ISSUE TITLE
create IoT Edge device failed in B1 basic tier hub

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#149]
install azure-iot-toolkit-1.3.0-rc3.vsix
step:

1.create IoT hub with B1 basic tier

2. create IoT Edge device failed,   is it expect? 
![image](https://user-images.githubusercontent.com/35018765/44653245-ca080a00-aa20-11e8-94a3-a30bb9190087.png)

**Comment by czgtest** [comment]
after https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-upgrade

it can create iot edge device ,  maybe it is expect.

**Comment by timwieman** [comment]
For posterity:  Per https://azure.microsoft.com/en-us/pricing/details/iot-hub/, Iot Edge is not supported on the Basic tier of IoT Hub.
