### ISSUE TITLE
The device info is not display in Output Channel after click IoT hub device

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#152]
test case :Get device info 

test step:
1.Click an IoT Hub device in tree explorer 
Expect : Verify a JSON of device info in shown in Output Channel, and the JSON contains the connection string of the device 

Actually : Verify nothing happens but just toggle the module list

**Comment by formulahendry** [comment]
It is by design with the new release of module list
