### ISSUE TITLE
Failed to list IoT Hub devices after change the time zone

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#161]
Toolkit : 1.3.0

1. select an IoT hub, verify the IoT Hub devices will display well
here time : 2018-9-12

2. change the time to 2018-9-11

3. click refresh button on toolkit 

verify Failed to list IoT Hub devices 

![image](https://user-images.githubusercontent.com/35018765/45403491-36c00d00-b68d-11e8-9656-0e3f4acc2bdb.png)

**Comment by formulahendry** [comment]
Depends on https://github.com/Azure/azure-iot-sdk-node/issues/365

**Comment by adashen** [comment]
close as time sync is the base requirement in client/server modal
