### ISSUE TITLE
Startup Activation time ...

### ISSUE THREAD

**Issue by Jaykul** [Microsoft/vscode-azure-iot-toolkit#167]
I've been getting popups from VS Code about the extension host "not responding" on startup **every time** lately, and when I look, it seems the works offender is the Azure IoT Toolkit at almost 10 seconds on my dev PC ...

- Extension Name: azure-iot-toolkit
- Extension Version: 1.4.0
- OS Version: Windows_NT x64 10.0.17763
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 9649,
		"activateCallTime": 11,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by formulahendry** [comment]
Hi @Jaykul , since `Azure IoT Toolkit` depends on the `Azure Account` extension, could you please also share the startup time of `Azure Account`? That would help us narrow down which extension takes most of time to start up.

**Comment by Jaykul** [comment]
I went to try and look this up for you and found I can't replicate the really long load times now. 

The only thing that _really_ changed is that I noticed that the _Python_ extension was taking _even longer_ than this, and figured out the reason was that it was searching for `python.exe` -- I configured the path for that in my settings, and it's now loading in under 1.5s ... which seems to have cascaded to everything else:

The Azure extensions all still appear slower than anything else, but no longer slow enough to trigger the "Extension Host is not responding" popup at startup...

![image](https://user-images.githubusercontent.com/192942/46310055-4942ad80-c58c-11e8-86a4-d64ad5022c1c.png)
