### ISSUE TITLE
Failed to list IoT Hub devices - Error: Unable to get local issuer certificate

### ISSUE THREAD

**Issue by znafz** [Microsoft/vscode-azure-iot-toolkit#183]
I have been following through the IoT Edge Quickstart/Tutorial on Windows 10. I am currently working through the Function deployment tutorial and I am seeing the below error after successfully logging in and selecting my IoT Hub. I am on a corporate network and have set up the http proxy setting both with and without credentials, along with disabling strict ssl, but I am still unable to list the hub devices.

![image](https://user-images.githubusercontent.com/10745968/46977889-5470ff80-d09b-11e8-8299-f1ba658bf433.png)

**Comment by znafz** [comment]
Hi @formulahendry  , unfortunately whitelisting domains in the firewall is not an option for me. However, I tried launching code with the various suggested flags (no-proxy-server, proxy-server, proxy-pac-url, ignore-certificate-errors) along with setting up the legacy proxy settings and still see the same error.

**Comment by formulahendry** [comment]
Have you tired the setting as https://stackoverflow.com/a/47571026/4545351 mentioned?

BTW, the issue would be related to VS Code editor, not this extension.  I would suggest you open issue to https://github.com/microsoft/vscode for more appropriate help.

**Comment by znafz** [comment]
That did not resolve the issue unfortunately. I'll open an issue with VS Code. Thanks for your help.
