### ISSUE TITLE
API of list device should return the info about whether the device is edge device

### ISSUE THREAD

**Issue by lirenhe** [microsoft/vscode-azure-iot-toolkit#185]
Please check the following issue for more details https://github.com/Microsoft/vscode-iot-workbench/issues/456

**Comment by formulahendry** [comment]
The return value of `getDevice` api already has this info:
![image](https://user-images.githubusercontent.com/1050213/47196586-e6c31d00-d393-11e8-8a68-e699e4bcb986.png)
Is it enough?

**Comment by lirenhe** [comment]
We would call getDevice function directly, can you have an parameter for getting non-edge device only?

**Comment by lirenhe** [comment]
We would call getDevice function directly, can you have an parameter for getting non-edge device only?

**Comment by formulahendry** [comment]
As workbench does not need API for now.
So closing it. Feel free to re-open or create a new issue if needed.
