### ISSUE TITLE
Failing to list devices on sidebar and single device deployment - Error: Socket hang up

### ISSUE THREAD

**Issue by znafz** [Microsoft/vscode-azure-iot-toolkit#189]
Hello,

I have set the VS Code proxy up via HTTP_PROXY and HTTPS_PROXY environment variables on Windows 10 in a corporate environment. This solved most of my connection issues, such as signing in, etc.. But the sidebar still does not list devices and shows an error: socket hang up. It also does not list devices when I try to create a deployment for a single device via the command palette. Oddly, I am able to list the devices when running the "Azure Iot Hub: List Devices" command in the command palette, and there is no significant delay in querying. Creating new devices works as well. How is it possible that listing devices via the command palette works but seems to fail everywhere else?
![image](https://user-images.githubusercontent.com/10745968/47453723-748b7780-d79b-11e8-8b06-76242f4d3a11.png)

**Comment by znafz** [comment]
Here is some more information that may be helpful:

Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
azure-iot-toolkit version: 1.5.0

**Comment by formulahendry** [comment]
Hi @znafz , could you please install the attached extension to see if device list could be shown?
[azure-iot-toolkit-1.5.1-sdk.zip](https://github.com/Microsoft/vscode-azure-iot-toolkit/files/2532742/azure-iot-toolkit-1.5.1-sdk.zip)
1. unzip the attached, you will see a zip file
2. Follow https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix to install it
3. After install is done, restart the VS Code

**Comment by znafz** [comment]
Fantastic! Thanks for your help! I am able to see the devices in the sidebar and "Create Deployment for Single Device". Unfortunately I am now seeing socket hang up errors for listing modules and deploying.
![image](https://user-images.githubusercontent.com/10745968/47810613-1e2db400-dd1a-11e8-81bb-9c8791ca93d7.png)

**Comment by formulahendry** [comment]
Hi @znafz , thanks for your information! 
For the proxy setting, did you try this to start VS Code with command line arguments? https://code.visualstudio.com/docs/setup/network#_proxy-server-support

**Comment by znafz** [comment]
Yes. I launched using the ignore-certificate-errors flag and proxy-pac-url set to my corporate pac url. Unfortunately the errors still occur.

**Comment by formulahendry** [comment]
Hi @znafz , it seems that some library used in the extension does not respect the proxy settings. I will investigate more about the root cause to see if we could have better support for the proxy environment.

**Comment by znafz** [comment]
Sounds great. Thanks for your help @formulahendry !

**Comment by formulahendry** [comment]
Hi @znafz , here is an updated version of the extension : 
[azure-iot-toolkit-1.6.1-sdk.zip](https://github.com/Microsoft/vscode-azure-iot-toolkit/files/2560194/azure-iot-toolkit-1.6.1-sdk.zip)

Please have a try, hope this version could work on your proxy environment.

**Comment by znafz** [comment]
Hi @formulahendry, the updated version has resolved all of my problems! Thank you for your help!
