### ISSUE TITLE
Add create deployment context menu to deloyment.XXX.json

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azure-iot-toolkit#198]

**Comment by formulahendry** [comment]
* Update context menu `when` logic
* Update template file check: https://github.com/Microsoft/vscode-azure-iot-toolkit/blob/4bfff9cb24cf5f7b42728640c4ed30bf2cda4253/src/iotEdgeExplorer.ts#L144

**Comment by formulahendry** [comment]
Released in v1.7.0
