### ISSUE TITLE
The API of selectIoTHub & createIoTHub do not work for Azure China

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-azure-iot-toolkit#200]
It looks those 2 APIs are stilling trying to do their work on global Azure.
Please check the following fix for IoT workbench:

https://github.com/Microsoft/vscode-iot-workbench/commit/156a34227e7cc41889bc1c2b7dc293f79dbe012a

**Comment by formulahendry** [comment]
Released in v1.7.0
