### ISSUE TITLE
Developers want to stop D2C monitoring in VS code

### ISSUE THREAD

**Issue by NT-D** [Microsoft/vscode-azure-iot-toolkit#218]
When we uses IoT Hub and this toolkit, it's common to monitor D2C messages. In VS Code menu, we can start D2C monitoring, but can't stop monitoring. Now we need to restart VS Code. Developers want to stop it from menu (Expected scenario is VS Code context menu have [Stop Monitoring D2C Messages])​

**Comment by formulahendry** [comment]
Hi @NT-D , there are two ways to Stop Monitoring D2C Messages, one is using `Command Palette`, another is using context menu of **OUTPUT** view, you refer to https://github.com/Microsoft/vscode-azure-iot-toolkit/wiki/Monitor-IoT-Hub-D2C-Message

![image](https://user-images.githubusercontent.com/1050213/49711608-41ce0d80-fc7b-11e8-962d-d9a4ab7284b8.png)

Do you think whether is it enough? The content menu of a device already have a lot of entry, we do not want to put to many into it. But we are considering add it in below place. What's your idea?

![image](https://user-images.githubusercontent.com/1050213/49711656-96718880-fc7b-11e8-8549-f4619b25db8a.png)

**Comment by czgtest** [comment]
@formulahendry  why not add the menu of stop monitoring D2C message for device ?

![image](https://user-images.githubusercontent.com/35018765/49844820-50ddc880-fdff-11e8-8ab3-670e1700f672.png)

**Comment by formulahendry** [comment]
>The context menu of a device already have a lot of entry, we do not want to put too many into it.

**Comment by formulahendry** [comment]
Hi @NT-D , we have added 'Stop Monitoring D2C Messages' in below place. So closing this issue.
![image](https://user-images.githubusercontent.com/1050213/49980067-d6db4a00-ff8c-11e8-963a-fa4c31f2e4ee.png)

Feel free to open a new issue or reopen this if you need any more help.

**Comment by NT-D** [comment]
@formulahendry Thank you very much!
