### ISSUE TITLE
[Rename] the command line of user setting in vscode is not changing name

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#222]
install toolkit 2.0.0-rc

1.open user setting in VS Code.

verify the command line is not changing name from 'Azure IoT Toolkit' to 'Azure IoT Hub Toolkit'

![image](https://user-images.githubusercontent.com/35018765/49843490-67cdec00-fdfa-11e8-8d8a-21d99115026c.png)

**Comment by formulahendry** [comment]
Yes, it is by design for backwards compatibility.

**Comment by czgtest** [comment]
it is not backwards for user

![image](https://user-images.githubusercontent.com/35018765/49844253-23901b00-fdfd-11e8-9dcc-edd2029542b6.png)

**Comment by formulahendry** [comment]
https://en.wikipedia.org/wiki/Backward_compatibility
