### ISSUE TITLE
send D2C message to IoT hub failed when device named "edgeDeviceC#"

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#223]
1.  set iot hub connect string

HostName=anotheriothub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=Ccwe/E/gHS7gIkvFTmxJpV2FMvlPLh8nQngabo96VgU=

2. Start monitoring D2C message for edgeDeviceC#
Verify ‘Start monitoring’ message is shown in Output Channel

![image](https://user-images.githubusercontent.com/35018765/49846963-c8fcbc00-fe08-11e8-883a-1b992138771f.png)

**Comment by formulahendry** [comment]
Duplicated with #95
