### ISSUE TITLE
How can I switch to another Microsoft Account  to connect with?

### ISSUE THREAD

**Issue by Fujiwo** [Microsoft/vscode-azure-iot-toolkit#225]
I cannot change my Microsoft Account after I signed in one of my Microsoft Accounts.
How can I switch to another Microsoft Account  to connect with?

Sign out button is necessary on the menu to switch Accounts.

**Comment by formulahendry** [comment]
Hi @Fujiwo , you could use `Command Palette` to `Sign Out`, then switch to another account.

![image](https://user-images.githubusercontent.com/1050213/50203299-fbc02a80-039b-11e9-8437-463f0264c516.png)
![image](https://user-images.githubusercontent.com/1050213/50203337-1b575300-039c-11e9-9adb-d6b1244da0a7.png)

BTW, the sign in/out feature is implemented by [Azure Account extension](https://github.com/Microsoft/vscode-azure-account) (IoT Hub Toolkit extension leverage this feature for azure login) . If you'd like to have a button, you could open a feature request to that repo.

Feel free to let me know if you need any other help

**Comment by Fujiwo** [comment]
Thanks, @formulahendry !
