### ISSUE TITLE
Devices are deleted without confirmation prompt

### ISSUE THREAD

**Issue by rdivossen** [Microsoft/vscode-azure-iot-toolkit#228]
In the contextmenu of IoTEdgeDevices there is the option "Delete Device".  Upon click, the device is deleted without asking for confirmation.  This is especially irritating if you wanted to click on "Refresh" which is right above "Delete Device" in the contextmenu.
PLEASE add a confirmation promt for deleting devices.

**Comment by formulahendry** [comment]
Hi @rdivossen  , in 2.1.0, we have added confirmation prompt. Please have a try.
