### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by NischalPV** [Microsoft/vscode-azure-iot-toolkit#229]
- Issue Type: `Performance`
- Extension Name: `azure-iot-toolkit`
- Extension Version: `2.0.0`
- OS Version: `Linux x64 4.19.12-1-MANJARO`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/nischal/vsciot-vscode.azure-iot-toolkit-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by formulahendry** [comment]
Hi @NischalPV , could you please attach the `/home/nischal/vsciot-vscode.azure-iot-toolkit-unresponsive.cpuprofile.txt` file?

**Comment by formulahendry** [comment]
Hi @NischalPV , in 2.1.0, we have use Webpack to improve the performance, so closing this issue. Feel free to reopen or create a new issue if you still meet with similar issue.
