### ISSUE TITLE
it will take about 5 second to response the stop action after click "Stop Monitoring D2C Message" in status bar 

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#238]
repro on : 2.1.0-rc

Right-click the title of tree explorer 
Click ‘Start monitoring D2C message’ 
Verify ‘Start monitoring’ message is shown in Output Channel 
Verify the is ‘Stop monitoring D2C message’ shown in Status Bar
Click ‘Stop monitoring D2C message’ in Status Bar

it will take about 5 second to response the stop action 
At first, I saw no response, and clicked the second time. then I see the stop result
![image](https://user-images.githubusercontent.com/35018765/50533313-1cd60780-0b62-11e9-9ab5-5b42e4271ea6.png)

**Comment by formulahendry** [comment]
Add hint message and hide the stop button right after it is clicked
![image](https://user-images.githubusercontent.com/1050213/50534109-bf968200-0b72-11e9-897b-c214a83b1eca.png)

Please test with new vsix.
