### ISSUE TITLE
Use VS Code clipboard API instead of clipboardy npm

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-azure-iot-toolkit#248]
* Change API
* Remove related webpack logic

https://code.visualstudio.com/updates/v1_30#_clipboard

https://code.visualstudio.com/updates/v1_29#_clipboard-api

https://code.visualstudio.com/api/references/vscode-api#Clipboard

**Comment by LazarusX** [comment]
Distribution of VS Code version in the past 28 days:
![image](https://user-images.githubusercontent.com/716650/50672559-de35c680-1013-11e9-9419-bc0f0fe4c1b8.png)

About 65% users use VS Code 1.30+

**Comment by formulahendry** [comment]
@LazarusX , great! Let's see if 1.30+ have more adoption in this or next Sprint, so that we could use the new VS Code clipboard API.

**Comment by LazarusX** [comment]
Over 80% now:

![image](https://user-images.githubusercontent.com/716650/51290844-f0fec100-1a3f-11e9-820d-26cc6bededd2.png)

**Comment by LazarusX** [comment]
Changes are ready on my side branch: https://github.com/Microsoft/vscode-azure-iot-toolkit/compare/ray-clipboard?expand=1

**Comment by formulahendry** [comment]
@LazarusX Awesome! You could send the PR after we release 2.2.0 .
