### ISSUE TITLE
Unable to monitor D2C messages in VS Code MessagingEntityNotFoundError

### ISSUE THREAD

**Issue by gastrocole** [Microsoft/vscode-azure-iot-toolkit#270]
Trying to monitor simulated temperature sensor messages in VS Code. Set up using this tutorial https://github.com/Microsoft/vscode-azure-iot-toolkit/issues/new on a RasPi using this tutorial https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm.

iotedge status is showing as running and all modules running, with temperature data being sent to logs every 5 seconds.
Azure portal showing that the hub is receiving messages when the iotedge service is running.

When selecting monitor D2C messages in vscode on the device:
![image](https://user-images.githubusercontent.com/12706836/52954881-2ff79d80-3383-11e9-99bd-04f4abf172f1.png)

I get the following error:
![image](https://user-images.githubusercontent.com/12706836/52954913-400f7d00-3383-11e9-9556-0a088dbb3f8f.png)

`[IoTHubMonitor] MessagingEntityNotFoundError: The messaging entity 'sb://ihsuprodmwhres019dednamespace.servicebus.windows.net/iothub-ehub-iotportabl-1279847-4e5c4aafc5/$management' could not be found. TrackingId:fcc88baa-a9a5-4f2d-a2da-bb824309d1ef_G0, SystemTracker:ihsuprodmwhres019dednamespace.servicebus.windows.net:iothub-ehub-iotportabl-1279847-4e5c4aafc5/$management, Timestamp:2019-02-18T13:33:20`

**Comment by formulahendry** [comment]
Hi @gastrocole , from the error log, this issue seems coming from service side.
Could you please try another IoT Hub and see if you still meet with this issue?

**Comment by gastrocole** [comment]
Closed issue as this is now working when I created a new hub. This error only appeared when I created the device id with underscores. Creating a new device without underscores didn't fix it. But creating a new hub did.
