### ISSUE TITLE
Changelog of 2.3.0 refers to non existing url

### ISSUE THREAD

**Issue by sandervandevelde** [Microsoft/vscode-azure-iot-toolkit#273]
The Changelog of 2.3.0 refers to the non existing https://docs.microsoft.com/nl-nl/azure/iot-hub/iot-hub-distributed-tracing .

I expect some background information on Azure IoT distributed tracing (preview). 

This results in a 404.

**Comment by formulahendry** [comment]
@sandervandevelde The url is expected to be available within one day. Stay tuned. 😄 
Let us know if you want to know anything more about Azure IoT distributed tracing.

**Comment by sandervandevelde** [comment]
@formulahendry Thanks for the quick update. 

Yes, I'm very interested.

**Comment by formulahendry** [comment]
Hi @sandervandevelde , thanks for your interest. The docs page is available now. There is also a blog post about this for your reference: https://devblogs.microsoft.com/iotdev/diagnose-issues-with-distributed-tracing-for-azure-iot-hub-preview-in-visual-studio-code/
Feel free to let us know if you'd like to know more about Azure IoT distributed tracing. :P
