### ISSUE TITLE
should not select an IoT Hub Device again when create deployment for Edge device 

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#277]
repro on : 2.3.0
vscode:1.31.1

steps:
Right click on an Edge device in device tree .
select Create deployment for Edge device .
then user need to select an IoT Hub Device again .

expect:
In select window, select the deployment.<defaultplatform>.json in config folder

**Comment by formulahendry** [comment]
Duplicated with #278
