### ISSUE TITLE
the page can't be found  in welcom page

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#282]
open welcome page in toolkit
click the link of "Quickly build your Azure IoT application with Node.js, Python or REST API"
open page 404 error.
https://devblogs.microsoft.com/iotdev/quickly-build-your-azure-iot-application-in-vs-code-with-node-js-python-or-rest-api/

**Comment by formulahendry** [comment]
Good catch! Please verify the fix with latest vsix: https://github.com/Microsoft/vscode-azure-iot-toolkit/releases/download/v2.4.0-rc2/azure-iot-toolkit-2.4.0-rc2.vsix

**Comment by czgtest** [comment]
fix work ,verify pass
