### ISSUE TITLE
Error if create options is larger then 512 bytes

### ISSUE THREAD

**Issue by C1oudNinja** [Microsoft/vscode-azure-iot-toolkit#293]
After the update to 2.5.0 it is not possible to have createOptions field larger then 512 byte. Priviously this was handeled by appending "createOptions01" see example below:
```
"{\"Env\":[\"_CX_LOGLEVEL=debug\",\"_CX_LOGCLEAR=true\",\"_CX_LOGFILESIZE=3\",\"_CX_LOGFILESAVED=2\"],\"Hostname\":\"cifxaccess\",\"HostConfig\":{\"Privileged\":true,\"Devices\":[{\"PathOnHost\":\"/dev/uio0\",\"PathInContainer\":\"/dev/uio0\",\"CgroupPermissions\":\"rwm\"}],\"PortBindings\":{\"62222/tcp\":[{\"HostPort\":\"62222\"}]},\"Mounts\":[{\"Target\":\"/app/appdata\",\"Source\":\"cifxaccess_data\",\"Type\":\"volume\",\"ReadOnly\":false,\"Consistency\":\"consistent\",\"VolumeOptions\":{}},{\"Target\":\"/app/logdata\",\"Source\":\"cifxaccess_log\",\"Type\":\"volume\",\"ReadOnly",
              "createOptions01": "\":false,\"Consistency\":\"consistent\",\"VolumeOptions\":{}}]}}"
```

But now the createOptions Validator says that its not a valid JSON, this is rigth but before the update to 2.5.0 it was a valid solution. If I delete this "createOptions01"  I get this error:
```
[Edge] Deployment failed. ArgumentError: Property or Tag value should be maximum 512 bytes. Error in Property/Tag
```
Do you have any ideas what to do here?

**Comment by xinyiz1226** [comment]
Thank you for reporting this issue. We just released a new version to fix this. Please use 2.5.1 to try and let us know if it resolves your issue. Thank you.

**Comment by C1oudNinja** [comment]
With version 2.5.1 it works again. Thank you for the fast fix.
