### ISSUE TITLE
the mouse is not focused on the menu when select a location to create IoT Hub

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#302]
step:
1.in command palette, "create IoT Hub"
2.select subscription
3.select a resource group to create your IoT hub
here the mouse is not focused on the menu, when user presses the next keyboard , she can not select resource group and continue
4.select a location to create your IoT hub
here the mouse is not focused on the menu too.

expect:
here the mouse is focused on the menu, when user presses the next keyboard , she can select resource group and continue

**Comment by formulahendry** [comment]
Out of scope.
Closing this.
