### ISSUE TITLE
Double select device ID when create module for edge device in treeview

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#303]
step:
1.create new edge device 
2.right-click the edge device and select "create module" menu
Actually:
it will let user to double select device ID for creating module
Except: 
let user to enter module ID to create module

**Comment by formulahendry** [comment]
Remove the context menu from 'Device', only show 'create module' in 'Modules'

Please test it: https://github.com/Microsoft/vscode-azure-iot-toolkit/releases/download/v2.6.0-rc2/azure-iot-toolkit-2.6.0-rc2.vsix

![image](https://user-images.githubusercontent.com/1050213/56569031-c7c77100-65ea-11e9-8d60-3966d76841c1.png)
