### ISSUE TITLE
IOT Central Support

### ISSUE THREAD

**Issue by stokes776** [microsoft/vscode-azure-iot-toolkit#307]
Does not seem to support Azure IOT Central. It idenfities it as an 'IoT Hubs' and when you try to drill into the resource, you receive an error: 

Cloud Explorer
The requested action could not be completed.
Details: Invalid length for a Base-64 char array or string.

![image](https://user-images.githubusercontent.com/50416033/57387265-9f5b7d00-717b-11e9-914e-9daae09728eb.png)

**Comment by blackchoey** [comment]
@stokes776 Do you means an Azure IoT Central application is listed under the "IoT Hubs" node? Could you share the version of Cloud Explorer and Visual Studio with us?

**Comment by stokes776** [comment]
Apologies, I cant seem to replicate whatever it was I did to get that error message. I am using Visual Studio 2017 15.9.11. I think I was trying to use the toolkit to access the underlying Hub of an IOTCentral deployment, and that is when that error popped up. I cant seem to find the Cloud Explorer Version number.

Since I cant replicate it, this can be deleted or marked as closed. Sorry about that.
