### ISSUE TITLE
the icon of the module is not changed to green and Sending D2C message’ message is not shown 

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#308]
step:
1.install edge extension
2.open custom vision gallery sample
3.Update the .env file with the values for your container registry and make sure that your docker engine has access to it
4.Build the entire solution by right-clicking on the deployment.template.json file and select Build and push IoT Edge Solution (this can take a while...especially to build open-cv, numpy and pillow...)
5.set up IoT edge simulator
6. run IoT edge solution in simulator
7.verify module  image-classifier-service is running in terminal penal of vscode.
but the icon of this module is not changed to green and not has ‘Connected (running)’ text

![image](https://user-images.githubusercontent.com/35018765/57422395-7a7e0d00-7242-11e9-8f51-a1741fd5a2c2.png)

8. start monitoring D2C message
verify Sending D2C message’ message is not shown in Output Channel 

![image](https://user-images.githubusercontent.com/35018765/57422514-ed878380-7242-11e9-8b94-f32911c2f69a.png)

**Comment by adashen** [comment]
The icon shows the connecting to edgeHub status while we now show the runnign status in the description. So the issue is not valid now.
