### ISSUE TITLE
Send D2C message not received 

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#316]
repro on toolkit v2.7.0-rc2

step:
1.IoT Hub selected: azure-iot-toolkit-test
2.Start monitoring Build-in event endpoint
3.select _0403 device and send D2C message to IOT hub
4.input message "test d2c"
5 check message not received from [_0403] device

here is the output 

[IoTHubMonitor] Start monitoring message arrived in built-in endpoint for [_0403] ...
[IoTHubMonitor] Created partition receiver [0] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [1] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [2] for consumerGroup [$Default]
[IoTHubMonitor] Created partition receiver [3] for consumerGroup [$Default]
[D2CMessage] Sending message to [IoT Hub] ...
[D2CMessage] [Success] Message sent to [IoT Hub]
[D2CMessage] Sending message to [IoT Hub] ...
[D2CMessage] [Success] Message sent to [IoT Hub]

expect : can see message received .
[IoTHubMonitor]  Message received from [_0403]:
"test d2c"

**Comment by formulahendry** [comment]
It will happen when selecting a new IoT Hub to monitor.
