### ISSUE TITLE
Rename 'Start Monitoring D2C Message' to 'Start Monitoring Built-in Event Endpoint' in welcome page

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#320]
repro on toolkit v2.7.0-rc
step
1.open welcome page
2.Rename 'Start Monitoring D2C Message' to 'Start Monitoring Built-in Event Endpoint'  
![image](https://user-images.githubusercontent.com/35018765/57768414-27262600-773e-11e9-8f9c-787298e83a03.png)

**Comment by formulahendry** [comment]
Updated
