### ISSUE TITLE
Show application and system properties for D2C messages

### ISSUE THREAD

**Issue by murdockcrc** [microsoft/vscode-azure-iot-toolkit#324]
Hi,

Is there a way for the toolkit's output to also show the system and application properties on IoT Hub messages (when monitoring the built-in endpoint)? It seems to me the output displays only the message's payload, and not these 2 additional attributes for the message.

The wiki does not explain how to achieve this (https://github.com/microsoft/vscode-azure-iot-toolkit/wiki/Monitor-IoT-Hub-Built-in-Event-Endpoint). Is there a vscode module setting we can edit to achieve the desired output?

**Comment by formulahendry** [comment]
Hi @murdockcrc , please check https://github.com/microsoft/vscode-azure-iot-toolkit#configuration .
You could use below setting to show more properties :
```json
{
    "azure-iot-toolkit.showVerboseMessage": true
}
```

**Comment by murdockcrc** [comment]
Yes, that's what I was looking for. May I suggest to add that content to the Wiki too, under the "Monitor IoT Hub Built in Event Endpoint" page? Thx for the pointer.

**Comment by formulahendry** [comment]
@murdockcrc , thanks for your feedback! Added that content to the Wiki.
