### ISSUE TITLE
the menu/icon of new edge device is not right 

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#331]
Step:
1.Create an Azure new VM , windows10 1809 with D2v3 size
2.install latest VS Code v1.35.1
3.install edge and toolkit extension 
![image](https://user-images.githubusercontent.com/35018765/59410486-89c91b00-8deb-11e9-9400-ebe5780fbde2.png)
4.select IoT Hub in toolkit
5.create IoT edge Device
![image](https://user-images.githubusercontent.com/35018765/59410703-225f9b00-8dec-11e9-89bf-16d2cf0fc491.png)
6.check the icon of edge device is not right and the menu is not right too
![image](https://user-images.githubusercontent.com/35018765/59410758-3b684c00-8dec-11e9-8bbe-a6914e9ef490.png)

![image](https://user-images.githubusercontent.com/35018765/59410818-65217300-8dec-11e9-803c-332523187322.png)

**Comment by tomaszbartoszewski** [comment]
I was able to reproduce the error, unfortunately I don't think I can fix it. Maybe it will be helpful for next person:

When adding device full device list refresh is triggered. Here two methods are called
https://github.com/microsoft/vscode-azure-iot-toolkit/blob/8f13066ecf07d1726446d1d79abe1314e396765f/src/utility.ts#L287

Then this query returns list without new device, it works with breakpoints as some caches are refreshed in IoT Hub and it returns new device.
https://github.com/microsoft/vscode-azure-iot-toolkit/blob/8f13066ecf07d1726446d1d79abe1314e396765f/src/utility.ts#L486

There is likely no need to refresh entire list, but the API only provides onDidChangeTreeData in TreeDataProvider, maybe creating new DeviceNode and passing it to this method could just get this device info from IoT Hub and add it to TreeView.

**Comment by formulahendry** [comment]
Upstream issue: https://github.com/Azure/azure-iot-sdk-node/issues/571

**Comment by blackchoey** [comment]
Close as upstream.
