### ISSUE TITLE
I want to localize command name to japanese

### ISSUE THREAD

**Issue by matsujirushi** [microsoft/vscode-azure-iot-toolkit#338]
Hi,
I want to localize command name to japanese.
What do I need to procedure?
(I can create the code and PR)

**Comment by formulahendry** [comment]
Hi @matsujirushi , thanks a lot for your passion for the localization! However, currently, our extension does not have a localization framework yet. So I will keep this open for tracking purpose.

**Comment by matsujirushi** [comment]
FYI
I trying to implement localization little bit.
https://github.com/matsujirushi/vscode-azure-iot-toolkit/commit/0ee89a7ef68fe0073aa1d9b4717a0a5339cadcfc
![image](https://user-images.githubusercontent.com/8079404/60811694-cb6e9b00-a1ca-11e9-9945-e58d56831114.png)

**Comment by formulahendry** [comment]
Hi @matsujirushi , that is really awesome! PR is welcome. 😄

**Comment by formulahendry** [comment]
Shipped in v2.9.0
Thanks @matsujirushi !
