### ISSUE TITLE
[Status] Send D2C message from edge device will cause "connectionState" become "Connected"

### ISSUE THREAD

**Issue by adashen** [microsoft/vscode-azure-iot-toolkit#371]
1. Send D2C message from an edge device
2. Refresh
3. The device icon becomes green.
4. After the message sent, it still green and not set back to blue

**Comment by njbuch** [comment]
I am seeing that the green/blue state changes are rather meaningless, or unpredictable. Think it should be debugged...

**Comment by adashen** [comment]
close as it is not reproduce now
