### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by adamlaska** [microsoft/vscode-azure-iot-toolkit#392]
- Issue Type: `Bug`
- Extension Name: `azure-iot-toolkit`
- Extension Version: `2.10.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by czgtest** [comment]
@adamlaska  Can you provide more information about this issue?

**Comment by czgtest** [comment]
duplicate with #397 ,close it

**Comment by adashen** [comment]
close as it is duplicate
