### ISSUE TITLE
use one channel to display D2C message or reminder user to switch channel for seeing D2C detail messages 

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#399]
Repro on : v2.11.0-rc
step:
1. right click one edge device 
2. start monitoring build-in event endpoint
here message will display in “Azure IoT Hub Toolkit” output channel.

3.send D2C message to IoT Hub and click send button.

Current behavior : 
here message will display in "Send D2C messages" channel, and only see summary information for sending messages,  
This behavior is very unintuitive to me :  

first,  the original behavior will display detail information of sending messages to user , now only summary information, and don't reminder user to see detail information in another output channel.

then .if user want to see detail info for sending messages, he must switch channels. this is not intuitive,  you can give me summary information , but don't let user switch channels.

**Comment by blackchoey** [comment]
Will not switch channel to "Send D2C messages" after discussion.

**Comment by czgtest** [comment]
step:
1.right click one edge device
2. start monitoring build-in event endpoint
here message will display in “Azure IoT Hub Toolkit” output channel.
3.send D2C message to IoT Hub and click send button.
latest behavior is the same as original .
it will show the detail information of sending D2C messages , 
if user want to see the summary info, he can switch to "Send D2C messages" channel

fix work, so close it
