### ISSUE TITLE
Inaccurate records of success and failure when cancel to send D2C message

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#401]
Repro on : v2.11.0-rc
step:
1. right-click the tree explorer
2. start monitoring build-in event endpoint
3. send D2C message to IoT Hub
4. select 2 devices to send message
5. check Data Template
6. click send , then cancel
7. check the result 
[11:52:27 AM] Start sending messages from 2 device(s) to IoT Hub.
[11:52:30 AM] User aborted.
[11:52:30 AM] 4 succeeded, and 0 failed.
Actually ,  each device send 6 messages.

**Comment by blackchoey** [comment]
This is by design. We already invoked api to send messages to IoT Hub but haven't received the callback yet. In this case the message will be sent to IoT Hub but not counted in our summary.
