### ISSUE TITLE
not validate Malformed dummy json syntax

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#402]
Repro on : v2.11.0-rc
step:
1.right-click the tree explorer
2.start monitoring build-in event endpoint
3.send D2C message to IoT Hub
4.select one device to send message
5. check Data Template
6. edit data template with wrong syntax, **but not validate Malformed dummy json syntax, can't see and error message.** 
![image](https://user-images.githubusercontent.com/35018765/66457608-5a79a080-eaa3-11e9-904a-99db84ac89d9.png)

7. click send button
8. verify the invalid message can be send ,
but the message format is different with valid template.  
do we need to help user validate the format of  Data Template? 

![image](https://user-images.githubusercontent.com/35018765/66457804-c2c88200-eaa3-11e9-837f-f68b5b9d7fb8.png)

if the data template is valid , here is the message
![image](https://user-images.githubusercontent.com/35018765/66457907-0622f080-eaa4-11e9-87b5-b31035caecb9.png)

**Comment by blackchoey** [comment]
This is by design. Data template is allowed to generate non-json message.
