### ISSUE TITLE
the running status is not displayed for edge module

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#403]
Repro on : v2.11.0-rc
step:
1. create edge device
2. set IoT edge simulator
3. run IoT edge in simulator
4. verify the running status of edge device module
the running status is not display
![image](https://user-images.githubusercontent.com/35018765/66469872-48a3f780-eabb-11e9-9350-226d05d59325.png)

**Comment by formulahendry** [comment]
It is by design. The edge module of simulator has not running status.
