### ISSUE TITLE
the device list  is not from sending message IoT Hub

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#404]
Repro on : v2.11.0-rc
step:
1. right-click one device in IoT hub "testhub1008.azure-devices.net"
2. send D2C message to IoT Hub
3. change 50 messages per device and select Data template
4. click send 
5. close the WebView of send D2C messages
6. select another IoT Hub "v-hub-zun" and open WebView of sending D2C message
 the progress bar is still there, and the progress is updated.  it is expected.
![image](https://user-images.githubusercontent.com/35018765/66471281-a2a5bc80-eabd-11e9-9a73-5e7973b91e18.png)
7. Wait the progress finished.
8.  select the devices in WebView, 
user can see the sending messages  to " testhub1008.azure-devices.net",  but the device list is from IoT Hub "v-hub-zun" ,  it is confuse.
![image](https://user-images.githubusercontent.com/35018765/66471746-7474ac80-eabe-11e9-85b1-5ba9bb9d59d0.png)

**Comment by blackchoey** [comment]
Fixed

**Comment by czgtest** [comment]
now the device list come from the right IoT Hub, close it
