### ISSUE TITLE
the color theme of D2C webview is not right when select "High Contrast" theme

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#405]
Repro on : v2.11.0-rc
step:
1. Press F1 and select "Preference: Color Theme"
2. select "High Contrast" theme
3. open WebView of Sending D2C message to IoT Hub
verify the WebView will use Light Theme.  it is not right.
please refer to welcome page  and keep consistent with it.

**Comment by blackchoey** [comment]
Confirmed with Tanya, our dark theme meets the high contrast requirements so will apply dark theme in high contrast theme

**Comment by czgtest** [comment]
Now the Web view will display dark theme in high contrast theme . close it
