### ISSUE TITLE
the running status will display "unknown"

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#408]
Repro on : v2.11.0-rc
step:
1. create edge device
2. create C# module in VS Code,  build and push IoT edge solution
3. create deployment for single device
here the status is running for c# module
![image](https://user-images.githubusercontent.com/35018765/66539867-5198d580-eb5c-11e9-9fe3-79cc062685cc.png)
4. stop edge runtime 
5. refresh the edge device, 
here the status is unknown for modules
![image](https://user-images.githubusercontent.com/35018765/66539901-80af4700-eb5c-11e9-8d2b-b68f436ccbd7.png)

**Comment by formulahendry** [comment]
As design
