### ISSUE TITLE
show output messages in "Send D2C Message" channel

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#415]
repro on v2.11.0

Scenario1 :
1. select one device and send D2C message 
2. wait the progress complete .
**Expect : show output messages in "Send D2C Message" channel
Actual:  not show output messages to user**

Scenaro2:  Pass
1. select one device and start monitoring build-in endpoint
here will switch to "Azure IoT Hub Toolkit" channel
2. send D2C message to device
3. wait the progress complete
4. show output messages in "Azure IoT Hub Toolkit" channel
it is expect

**Comment by blackchoey** [comment]
This is by design according to the discussion around https://github.com/microsoft/vscode-azure-iot-toolkit/issues/399
