### ISSUE TITLE
some projects miss loading

### ISSUE THREAD

**Issue by pw007** [microsoft/vscode-azure-iot-toolkit#416]
When I Open the remote-monitoring-services-dotnet-master\storage-adapter folder in Visual Studio Code.  VS shows: some projects loading error like these:[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\WebService.Test\WebService.Test.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        检测到的包版本在依赖项约束之外: Microsoft.Azure.KeyVault.WebKey 2.0.4 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。
[warn]: OmniSharp.MSBuild.ProjectLoader
        检测到的包版本在依赖项约束之外: Microsoft.Rest.ClientRuntime 2.3.2 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\WebService.Test\WebService.Test.csproj'.
c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\WebService.Test\WebService.Test.csproj
c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\WebService.Test\WebService.Test.csproj(0,0): Error: 检测到的包版本在依赖项约束之外: Microsoft.Azure.KeyVault.WebKey 2.0.4 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。
c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\WebService.Test\WebService.Test.csproj(0,0): Error: 检测到的包版本在依赖项约束之外: Microsoft.Rest.ClientRuntime 2.3.2 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\WebService.Test\WebService.Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Services.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        检测到的包版本在依赖项约束之外: Microsoft.Azure.KeyVault.WebKey 2.0.4 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。
[warn]: OmniSharp.MSBuild.ProjectLoader
        检测到的包版本在依赖项约束之外: Microsoft.Rest.ClientRuntime 2.3.2 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Services.csproj'.
c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Services.csproj
c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Services.csproj(0,0): Error: 检测到的包版本在依赖项约束之外: Microsoft.Azure.KeyVault.WebKey 2.0.4 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。
c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Services.csproj(0,0): Error: 检测到的包版本在依赖项约束之外: Microsoft.Rest.ClientRuntime 2.3.2 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services\Services.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services.Test\Services.Test.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        检测到的包版本在依赖项约束之外: Microsoft.Azure.KeyVault.WebKey 2.0.4 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。
[warn]: OmniSharp.MSBuild.ProjectLoader
        检测到的包版本在依赖项约束之外: Microsoft.Rest.ClientRuntime 2.3.2 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services.Test\Services.Test.csproj'.
c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services.Test\Services.Test.csproj
c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services.Test\Services.Test.csproj(0,0): Error: 检测到的包版本在依赖项约束之外: Microsoft.Azure.KeyVault.WebKey 2.0.4 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。
c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services.Test\Services.Test.csproj(0,0): Error: 检测到的包版本在依赖项约束之外: Microsoft.Rest.ClientRuntime 2.3.2 需要 Newtonsoft.Json (>= 9.0.1 && < 10.0.0)，但版本 Newtonsoft.Json 10.0.3 已解决。

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\temp\remote-monitoring-services-dotnet-master\storage-adapter\Services.Test\Services.Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: WebService

**Comment by czgtest** [comment]
@pw007    do you use Azure IoT Hub Toolkit?   Toolkit don't need to load project .

**Comment by adashen** [comment]
Close as there is no response from customer and it is not related to toolkit.
