### ISSUE TITLE
VS Code disconnects from WSL after 1.39 update

### ISSUE THREAD

**Issue by ahernandez-allegion** [microsoft/vscode-azure-iot-toolkit#421]
Issue Type: **Bug**

I had initially filed an issue for Remote-WSL but they asked me to report it over here:

https://github.com/microsoft/vscode-remote-release/issues/1646

After the automatic update to 1.39, the WSL extension is disconnecting from WSL. This happens after I manually connect, run `code .` from WSL, or use "Open Recent". It seems to connect briefly for about 5 seconds then disconnects and gives me this pop-up:

"Cannot reconnect. Please reload the window".

It gives me two options: Reload window or Cancel. If I Reload window, it just happens again.

![image](https://user-images.githubusercontent.com/49734333/67496629-ee1da600-f639-11e9-877d-9f722958163c.png)

I've been working in VS Code with WSL perfectly fine today until after the update.

After further research, the extension **Azure IoT Device Workbench** was causing the problem. Disabling the extension allows me to continue using Remote-WSL. The WSL log does not show anything notable. There does not appear to be any settings for this extension but I have the following information:

```
Name: Azure IoT Device Workbench
Id: vsciot-vscode.vscode-iot-workbench
Description: Integrated environment to enable easy development on IoT prototype devices (e.g. MXChip IoT DevKit, teXXmo IoT Button, ESP32 and Raspberry Pi) with multiple Azure services.
Version: 0.10.15
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-iot-workbench
```

VS Code info:

```
Version: 1.39.0 (user setup)
Commit: 9df03c6d6ce97c6645c5846f6dfa2a6a7d276515
Date: 2019-10-09T06:58:04.439Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Extension version: 0.39.9
VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.4.0-17763-Microsoft
```

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (6.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-17763-Microsoft|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 2712)|
|Memory (System)|15.78GB (6.22GB free)|
|VM|0%|
</details>

**Comment by czgtest** [comment]
@ahernandez-allegion , here is the right path for [Azure IoT Device Workbench ](https://github.com/microsoft/vscode-iot-workbench/issues)

**Comment by zunhu** [comment]
it is known issue, fixed and will release new version of workbench in next week.

**Comment by czgtest** [comment]
@ahernandez-allegion  this issue is fixed in the latest Azure IoT Device Workbench v0.10.16,  you can upgrade to latest version and use it again.

**Comment by ahernandez-allegion** [comment]
> @ahernandez-allegion this issue is fixed in the latest Azure IoT Device Workbench v0.10.16, you can upgrade to latest version and use it again.

This is resolved now, thank you!
