### ISSUE TITLE
Unable to connect to IoT Hub default endpoint

### ISSUE THREAD

**Issue by ggirard07** [microsoft/vscode-azure-iot-toolkit#438]
### Steps to reproduce

1. Install extension on fresh VS Code install.
2. Connect to Azure IoT Hub.
3. Start monitoring D2C messages by connecting to default endpoint. Right click on either
   - Endpoints > Built-in endpoints > events
   - Devices > MyDevice 

### Expected result

Connection is successful and messages show up in console.

### Actual result

Connection fails with following message:
```log
[IoTHubMonitor] The filter 'amqp.annotation.x-opt-enqueued-time > 'NaN'' is not a valid amqp filter for EventHub entities TrackingId:9307c92c-3402-4aa5-b977-725dbb80998f_B12, SystemTracker:ihsuprodblres003dednamespace:eventhub:iothub-ehub-dcshared-f-2328165-c78ac3f756~16383, Timestamp:2019-12-16T19:28:00 Reference:4841db24-73cc-401a-bf01-6d25f60ac15f, TrackingId:0bf3f242-1f4d-43fe-99db-07b0d7c4f1cc_B12, SystemTracker:ihsuprodblres003dednamespace:eventhub:iothub-ehub-dcshared-f-2328165-c78ac3f756~16383|$default, Timestamp:2019-12-16T19:28:00 TrackingId:4b5b2f7f59394ae894cad78fec6ef6f3_G2, SystemTracker:gateway7, Timestamp:2019-12-16T19:28:00
```

### Remarks

I also noticed that a default setting value seemed in error in the extension configuration.  
I tried to fix it by setting any value, but I can't as VS Code seemed unable to save the value (`Unable to write to User Settings because azure-iot-toolkit.monitorD2CBeforeNowInMinutes is not a registered configuration`).  
I don't know whether both issues are actually related as they are both about timespan values.

**Comment by formulahendry** [comment]
Hi @ggirard07 , could you please kindly share more info so that we could have deep inestigation?

1. Have a screenshot of your settings.json file.
2. Try to use another IoT Hub to make sure it is not issue of IoT Hub it self

**Comment by ggirard07** [comment]
@formulahendry I tried with the [Azure IoT Explorer app](https://github.com/Azure/azure-iot-explorer) and had no issue connecting to same endpoint/same consumer group on the exact same hub from the same machine.  
I'll provide my settings.json file later as this was my home machine.

**Comment by ggirard07** [comment]
Looks like all I needed to do to get things working properly was to restart my VS Code instance...
Now monitoring the built-in event endpoint is working properly.
The setting default value seems fine too now
![image](https://user-images.githubusercontent.com/2625886/71041737-cc9be080-20f7-11ea-810a-8acbd17e8042.png)

VS Code 1.41.0 with Azure IoT Tools extension v0.3.0

**Comment by formulahendry** [comment]
Hi @ggirard07 , good to know that everything is working now! 😄 
So closing this issue.
