### ISSUE TITLE
Cannot set property '_isLoadingMore' of undefined when Azure IoT Hub device provisioning service : load more

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#447]
repro on v2.15.0-rc

get error when run "Azure IoT Hub device provisioning service : load more" 

Error: Cannot set property '_isLoadingMore' of undefined

![image](https://user-images.githubusercontent.com/35018765/71456075-b3b7bd00-27d2-11ea-8c72-d7ed5b6494ca.png)

**Comment by formulahendry** [comment]
@blackchoey Please help take a look, thanks!

**Comment by blackchoey** [comment]
@formulahendry The loadMore command is hidden previously. Following commit shows it in command palette: https://github.com/microsoft/vscode-azure-iot-toolkit/commit/01b4c7222831be4a42ed3b5d5e5ffb92eb7e292d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
Please hide it again. Thanks.
