### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bguerreropuga** [microsoft/vscode-azure-iot-toolkit#451]
- Issue Type: `Performance`
- Extension Name: `azure-iot-toolkit`
- Extension Version: `2.15.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\bguer\vsciot-vscode.azure-iot-toolkit-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by czgtest** [comment]
@bguerreropuga  could you share the C:\Users\bguer\vsciot-vscode.azure-iot-toolkit-unresponsive.cpuprofile.txt file, so that we could do investigation.

**Comment by czgtest** [comment]
@formulahendry    here is the step about how to find vsciot-vscode.azure-iot-toolkit-unresponsive.cpuprofile.txt.
1.run command "Developer: show running extensions" in vscode
2.check the performance issue of Azure IoT hub
![image](https://user-images.githubusercontent.com/35018765/72231447-6458f580-35f6-11ea-825b-aeb623014de2.png)

**Comment by rpus** [comment]
Hi... Here's a file from me (as I just got the modern equivalent of this issue):

[vsciot-vscode.azure-iot-toolkit-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-azure-iot-toolkit/files/4442626/vsciot-vscode.azure-iot-toolkit-unresponsive.cpuprofile.txt)

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by formulahendry** [comment]
Hi @rpus , thanks for your logs file!
After investigating the logs, we need more information from your side:

- Could you tell how the CPU high load would affect on the usage of VS Code?
- From the logs, I see there are several extension in your VS Code. As all the extensions are running in on process, they may have impact on each other. Would you please only enable this extension and see whether the issue still exists?

**Comment by rpus** [comment]
Hi... I don't have any practical problem; I just though I would post some representative logs as they were missing from the original post of this issue, and I got the same issue/message myself. If the logs don't lead you to any obvious general improvement (like using webpack, which often cones up in this kind of discussion), then I guess all is well here!

Thanks for the reply.

**Comment by formulahendry** [comment]
Got it! Thanks for your reply and information.
If you meet with this issue again and affect the VS Code as practical problem. Feel free to provide other logs if you have. Then we will have more investigation on this.
We will keep this issue open for some days in case you have any other input.

**Comment by formulahendry** [comment]
Closing this issue.
Feel free to reopen this issue or create a new issue if you have any other information or you meet with this issue again which affects the VS Code.
