### ISSUE TITLE
Use Marketplace for temp sensor module - CreateOptions should be string

### ISSUE THREAD

**Issue by PeterHedley94** [microsoft/vscode-azure-iot-toolkit#456]
Issue Type: <b>Bug</b>

I have created a simple IOT solution using the IOT Tools extension. I select module from marketplace, temp sensor. Then when right click `create deployment from single...` then select that deployment it first says  `Please select deployment manifest file under 'config' folder for deployment.` Then I move it to the config folder and I get ```There are errors in deployment json file: data should NOT have additional properties, data.modulesContent.$edgeAgent['properties.desired'].systemModules.edgeAgent.settings.createOptions should be string, ```. I have tried this on two separate computers. Both times it fails. Given this commit from a microsoft repo I was trying to use https://github.com/Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi/commit/6fcd8cafe126ab7b02c0775912a41c3c1bd2e2c9 it seems my extension is miles behind. But I have only just installed it! What is going on?

Extension version: 2.16.0
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor (16 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.34GB (0.54GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by czgtest** [comment]
you need to `generate IoT edge deployment mainfest` before `create deployment from single device`,
here is the step:
1.right-click the deployment.template.json and select `generate IoT edge deployment mainfest` 
2. right-click the generate deployment file in config folder (eg config/deployment.amd64.json)and  select  `create deployment from single device`
3. check the deployment result

**Comment by czgtest** [comment]
@PeterHedley94  Any update from you, do you resolve this issue ?

**Comment by PeterHedley94** [comment]
Hi @czgtest yes solved, thank you very much for the help. New to this and was definitely not a bug so will close the issue
