### ISSUE TITLE
[EventHubMonitor] Error: The subscription '97393ea4-9a50-47a2-9583-xxxxxx' could not be found

### ISSUE THREAD

**Issue by chris-han** [microsoft/vscode-azure-iot-toolkit#468]
When I try 'Start Monitoring' a customer Event hub, I got this error right after the status message: 
[EventHubMonitor] Start monitoring message arrived in custom Event Hub endpoint [streaming-east2] ...

I'm using China Cloud. Monitoring the Built-in endpoint works fine though.

**Comment by formulahendry** [comment]
Hi,
Please refer to https://github.com/microsoft/vscode-azure-iot-toolkit/issues/461
