### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by hvuSyslogic** [microsoft/vscode-azure-iot-toolkit#480]
- Issue Type: `Bug`
- Extension Name: `azure-iot-toolkit`
- Extension Version: `2.16.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by czgtest** [comment]
duplicate with issue #481
