### ISSUE TITLE
Azure IoT SaS token stored? and How to revoke?

### ISSUE THREAD

**Issue by nishad1092** [microsoft/vscode-azure-iot-toolkit#482]
Hi, 
I have two queries,

1. Once I create SaS token for IoT Hub, where is it stored or is it stored anywhere in Azure?
2. How to revoke the Old SaS Token.

**Comment by formulahendry** [comment]
Hi @nishad1092 ,

1. Are you using this extension to create the SaS token? This extension does not store the SaS token.
2. Per the document https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security#security-tokens, it did not mention about how to revoke the Old SaS Token. But you could set the expiry time of your SaS token when you create it.

**Comment by nishad1092** [comment]
Hi @formulahendry , 

1. By whatever means I create SAS token, whether it be VS code or through programmaticaly, Where does it get stored?
2. Expiry time, yes. But there is no way to revoke old ones? because It looks dangerous if the SAS token is hanging around which has not expired because I have created few for testing purpose for my IoT Hub.

**Comment by formulahendry** [comment]
For the question you asked, it is not related to the VS Code extension. So I suggest you ask these questions in a proper place, as this GitHub repo is for the VS Code extension not the IoT Hub service.

**Comment by nishad1092** [comment]
Sure will do

**Comment by nishad1092** [comment]
But I wanted to know if I create frm VS code too. Because for testing, Im doing it frm VScode.

**Comment by formulahendry** [comment]
For VS Code, it does not store SAS token.
Closing this issue.
Feel free to create a new issue or reopen this if you need more help.
