### ISSUE TITLE
 Azure IoT Hub extension throws validation error if any create options are specified for any custom modules

### ISSUE THREAD

**Issue by toolboc** [microsoft/vscode-azure-iot-toolkit#511]
Ex: Given the following entry in a deployment.template.json:

        "modules": {
          "YoloModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULES.YoloModule}",
              "createOptions": {
                "Env": [
                  "VIDEO_PATH=$CONTAINER_VIDEO_SOURCE",
                  "VIDEO_WIDTH=0",
                  "VIDEO_HEIGHT=0",
                  "FONT_SCALE=0.8"
                ]
              }
            }
          }
        }
Will result in an error when attempting to "Create Deployment to a Single Device" from VS Code with:

![image](https://user-images.githubusercontent.com/2018336/110384422-3bc66300-8023-11eb-9fe9-d02d9b67c601.png)

```
There are errors in deployment json file: data.modulesContent.$edgeAgent['properties.desired'].modules['YoloModule'].settings should NOT have additional properties
```

![image](https://user-images.githubusercontent.com/2018336/110384385-2bae8380-8023-11eb-9acd-9d6d13fa69ca.png)

This deployment configuration in question has worked without issue since July 2019, and only started receiving reports of being broken since the latest update to the IoT Hub extension which was released 6 days ago. The deployment in question can be seen here: https://github.com/toolboc/IntelligentEdgeHOL/blob/master/deployment.template.json

Other users are reporting similar issues, the problem is in the schema validation, it is assuming that ANY entries aside from image for ANY custom module is invalid. This is going to break ALOT of deployments:

microsoft/vscode-azure-iot-toolkit#499

For reference, the deployment in question, applies just fine using the Azure CLI directly, this is likely an issue in the schema validation of the IoT Hub extension:

![image](https://user-images.githubusercontent.com/2018336/110384328-16395980-8023-11eb-8b72-220a4330a95e.png)

**Comment by c-ryan-k** [comment]
@toolboc thanks for bringing this to our attention! It seems there's a conflict with the schema we are using to validate the deployment JSON specifically related to the formatting of `createOptions` - as the schema currently only supports a single string value. Until we can resolve this conflict by modifying the schema or adjusting validation - a workaround (like you mentioned) will be to use the CLI or Azure portal for these deployments.

**Comment by montgomp** [comment]
Ensure that you are stringifying the createOptions object being submitted. A resent release should now be doing the "chunking" of the stringified object into multiple properties as needed.

**Comment by montgomp** [comment]
See also: https://github.com/SchemaStore/schemastore/commit/c43c9e8264adc1e1a1308399428e0bb6d14b2b32
