### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rebootxxxi** [microsoft/vscode-azure-iot-toolkit#523]
- Issue Type: `Bug`
- Extension Name: `azure-iot-toolkit`
- Extension Version: `2.16.6`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by montgomp** [comment]
Please provide detailed information. I will re-open when we have actionable items.
