### ISSUE TITLE
No friendly info when there is no subscriptions

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode-azure-iot-toolkit#67]
![snipaste20180302_155950](https://user-images.githubusercontent.com/1621293/36889461-03f141c8-1e35-11e8-9f71-ee62b1ddd75f.png)

Desired behavior:

![snipaste20180302_161130](https://user-images.githubusercontent.com/1621293/36889471-122308a8-1e35-11e8-88fb-2f68faff17e7.png)

**Comment by formulahendry** [comment]
Shipped in v1.6.0
