### ISSUE TITLE
Check compatibility with IoT Hub Basic tier

### ISSUE THREAD

**Issue by LazarusX** [microsoft/vscode-azure-iot-toolkit#81]
The new IoT Hub Basic tier does not support monitoring, C2D messaging, device management, device twin and Edge (see [IoT Hub pricing](https://azure.microsoft.com/en-us/pricing/details/iot-hub/)). We need to check the compatibility with it.

**Comment by formulahendry** [comment]
![image](https://user-images.githubusercontent.com/1050213/71398704-45e98500-265c-11ea-920c-052a31cf66b6.png)
We will show error message given from server side. No need to have extra logic to check compatibility.
