### ISSUE TITLE
List iot hub after selecting subscription would fail randomly

### ISSUE THREAD

**Issue by lirenhe** [microsoft/vscode-azure-iot-toolkit#83]
Repo step:
Open new window of vscode, select iothub, then select subscription.
sometimes, the list of iothub is not listed. It happens more often if you just open a new VS code.

Note: the problem happened randomly. In most cases, it works fine.

**Comment by formulahendry** [comment]
This issue is from VS Code. Bug is reported to vscode repo: https://github.com/Microsoft/vscode/issues/48879
