### ISSUE TITLE
Invoke Direct Method  will fail when device name  contains’#’

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-toolkit#92]
Test steps:
1.	create device  named  “testc#”
2.	create invoke method from here https://iotdevtool.azurewebsites.net/device/ 
3.	right-click the testc# device and select “Invoke Direct Method”
![image](https://user-images.githubusercontent.com/35018765/40097609-aa1ef644-5909-11e8-92e5-9071030767fe.png)

**Comment by formulahendry** [comment]
Upstream issue: https://github.com/Azure/azure-iot-sdk-node/issues/289

**Comment by czgtest** [comment]
“testc#” device can create succesfully now in v1.1.0
