### ISSUE TITLE
Monitor C2D message will fail when device name contains’#’

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#94]

**Comment by czgtest** [comment]
![image](https://user-images.githubusercontent.com/35018765/40103238-5673b5dc-591f-11e8-9397-8f8520880424.png)

**Comment by formulahendry** [comment]
Upstream issue: https://github.com/Azure/azure-iot-sdk-node/issues/290

**Comment by formulahendry** [comment]
From SDK side: `For all intent and purposes I'd say the # sign isn't supported in device ids.`
So closing this.
